<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * 
 * Implements hook_help().
 */

// function hello_world_help($route_name, RouteMatchInterface $route_match)
// {

//     switch($route_name) {

//         case 'help.page.hello_world':

//             $output = '';
//             $output .= '<h3>' . 'this is an example' . '</h3>';
//             $output .= '<p>' . 'this is an example' . '</p>';

//             return $output;

//             default:
//     }
// }
