<?php

/***
Implements hook_cron()

@file
This file demonstrates how to use hook functions
 ***/





function mymodule_cron()
{
    \Drupal::messenger()->addMessage("Hello from mymodule cron :) :))");
}


/**
 *  Implements hook_form_alter 
 */

function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    \Drupal::messenger()->addMessage("form_id of this form is @id: " . $form_id);

    if ($form_id == 'node_pak_blogs_edit_form') {
        $form['actions']['submit']['#value'] = 'happy saving the node';
    }
}
